contact_form_action = "#"
copyright = "Copyright by your company"
custom_script = ""
purge_css = true
theme_copyright = true
favicon = "images/favicon.png"
logo = ""
logo_text = "Dot"
logo_width = "100px"
image_gallery = true
google_adsense = ""
google_tag_manager = ""
logo_webp = true

[contact_info]
address = "9567 Turner Trace Apt. BC C3G8A4"
email = "info@email.com"
mobile = "+211234565523"

[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

[crisp_chat]
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d"
enable = false

[preloader]
enable = true
preloader = ""

[search]
enable = true
primary_color = "#02007e"
include_all_sections = true
show_image = false

[metadata]
author = "Themefisher"
description = "This is meta description"
image = "images/favicon.png"
keywords = [ "Boilerplate", "Hugo", "Themefisher", "GetHugoThemes" ]

[site_verification]
bing = ""
google = ""
baidu = ""
facebook = ""
mastodon = ""

[[social]]
title = "facebook"
icon = "ti-facebook"
link = "#"

[[social]]
title = "twitter"
icon = "ti-twitter-alt"
link = "#"

[[social]]
title = "github"
icon = "ti-github"
link = "#"

[[social]]
title = "linkedin"
icon = "ti-linkedin"
link = "#"