contact_form_action = "#"
custom_script = ""
purge_css = true
favicon = "images/favicon.png"
logo = ""
logo_text = "Dottsy"
logo_width = "1000px"
image_gallery = true
google_adsense = ""
google_tag_manager = ""
copyright = "Copyright by your company"
theme_copyright = true
logo_webp = true

[contact_info]
address = "9567 Turner Trace Apt. BC C3G8A4"
email = "info@email.com"
mobile = "+211234565523"

[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

[crisp_chat]
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d"
enable = false

[preloader]
enable = true
preloader = ""

[search]
enable = true
primary_color = "#ff2f92"
include_all_sections = true
show_image = false

[metadata]
author = "Me"
description = "Meta wub dub"
image = "images/favicon.png"
keywords = [ "Happy happy", "Brappy", "Crappy" ]

[site_verification]
bing = ""
google = ""
baidu = ""
facebook = ""
mastodon = ""

[[social]]
title = "facebook"
icon = "ti-facebook"
link = "https://www.facebook.com"

[[social]]
title = "twitter"
icon = "ti-twitter-alt"
link = "https://www.twitter.com"

[[social]]
title = "github"
icon = "ti-github"
link = "https://www.github.com"

[[social]]
title = "linkedin"
icon = "ti-linkedin"
link = "https://www.linkedin.com"